---
- name: Deploy multiple duplicate cloud instances in OpenStack
  hosts: localhost

  tasks:
    - name: Launch web instances
      os_server:
        state: present
        auth:
          auth_url: "https://openstack.acg.maine.edu:5000/v2.0/"
          username: "{{ username }}"
          password: "{{ password }}"
          project_name: "{{ item.project }}"
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        key_name: "{{ item.key_name }}"
        flavor: "{{ item.flavor }}"
        boot_from_volume: True
        volume_size: "{{ item.size }}"
        security_groups: "{{ item.groups }}"
        network: "{{ item.network }}"
        auto_ip: yes
      register: newnodes
      with_items: "{{ servers }}"

    - add_host: name={{ item.server.public_v4 }} groups=created_nodes ansible_user=ubuntu
      with_items: "{{ newnodes.results }}"
      when: "'Ubuntu' in \"{{ item.server.volumes[0].volume_image_metadata.image_name }}\""
      
    - add_host: name={{ item.server.public_v4 }} groups=created_nodes ansible_user=centos
      with_items: "{{ newnodes.results }}"
      when: "'CentOS' in \"{{ item.server.volumes[0].volume_image_metadata.image_name }}\""
      
    - local_action: wait_for port=22 host="{{ item.server.public_v4 }}" search_regex=OpenSSH delay=10
      with_items: "{{ newnodes.results }}"
