---
- include: create-server.yml

- name: Provision servers
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Install python
      raw: sudo apt-get -y install python
      ignore_errors: yes
    
    - name: Install python
      raw: sudo yum -y install python
      ignore_errors: yes
    
    - name: Gathering facts
      setup:
 
  roles:
    - role: common
