---
- include: create-server.yml

- name: Provision servers
  hosts: all
  pre_tasks:
    - name: Install python
      raw: apt-get -y install python
      when: ansible_distribution == "Ubuntu"
    
    - name: Install python
      raw: yum -y install python
      when: ansible_distribution == "CentOS"
 
  roles:
    - role: common

