---
- include: create-server.yml

- name: Provision servers
  hosts: all
  pre_tasks:
    - name: Install python
      raw: apt-get -y install python
    
    - name: Install python
      raw: yum -y install python
 
  roles:
    - role: common

