---
  - raw: apt-get -y install python-simplejson
    when: ansible_distribution == "Ubuntu"
    
  - raw: yum -y install python-simplejson
    when: ansible_distribution == "CentOS"
    
  - name: Update package cache.
    apt: name={{ item }} state=installed update-cache=yes
    with_items:
      - git
      - wget
    when: ansible_distribution == "Ubuntu"
    
  - name: Update package cache.
    yum: name={{ item }} state=installed update-cache=yes
    with_items:
      - git
      - wget
    when: ansible_distribution == "CentOS"
  
  - name: Download ACG suite
    action: shell wget https://raw.githubusercontent.com/UMaineACG/ACG-Package-Suite/master/starter.sh
    
  - name: Setup ACG suite
    action: shell sh starter.sh
