---
  - name: Update package cache.
    apt: pkg={{items}} state=installed update-cache=yes
    with_items:
      - git
      - wget
  
  - name: Download ACG suite
    action: shell wget https://raw.githubusercontent.com/UMaineACG/ACG-Package-Suite/master/starter.sh
    
  - name: Setup ACG suite
    action: shell sh starter.sh
